version: '2'
services:
  db:
    container_name: hello.db
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4
    ports:
      - 8080:8080

  web_api_test:
    container_name: hello.web
    image: ${DOCKER_REGISTRY-}webapitest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    links:
      - db
  
  #reverse-proxy:
  #  container_name: hello.proxy
  #  image: nginx
  #  depends_on:
  #    - web_api_test
  #  networks:
  #    vpcbr:
  #      ipv4_address: 10.5.0.6
  #  ports:
  #    - "9090:9090"
  #  volumes:
  #    - ./proxy.conf:/etc/nginx/conf.d/default.conf

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1