version: '3.4'

services:
  db:
    container_name: hello.db
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - local_container
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    networks:
      - local_container
    ports:
      - 8080:8080

  web_api_test:
    image: ${DOCKER_REGISTRY-}webapitest
    restart: always
    build:
      context: .
      dockerfile: web_api_test/Dockerfile
    networks:
      - local_container
    ports:
      - 5000:80
      - 5001:443

  nginx:
    container_name: hello.nginx
    image: nginx:latest
    restart: always
    networks:
      - local_container
    depends_on:
      - web_api_test
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      #- ./proxy.conf:/etc/nginx/conf.d/default.conf

networks:
  local_container:
    driver: bridge